/*
 * generated by Xtext
 */
package org.sprat.ecosystem.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EcosystemUiModule extends org.sprat.ecosystem.ui.AbstractEcosystemUiModule {
	public EcosystemUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return EcosystemAntlrTokenToAttributeIdMapper.class ;
	}
}
