/*
 * generated by Xtext
 */
package org.sprat.ecosystem;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.sprat.ecosystem.converter.ExtraTerminalConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EcosystemRuntimeModule extends org.sprat.ecosystem.AbstractEcosystemRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return ExtraTerminalConverters.class;
	}
}
