/*
* generated by Xtext
*/
package org.sprat.ecosystem;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EcosystemStandaloneSetup extends EcosystemStandaloneSetupGenerated{

	public static void doSetup() {
		new EcosystemStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

